# language: ruby
# sudo: required
# rvm:
#   - "1.8.7"
#   - "1.9.2"
#   - "1.9.3"
#   - jruby-18mode # JRuby in 1.8 mode
#   - jruby-19mode # JRuby in 1.9 mode
#   - rbx

# language: ruby
# rvm:
#   - 2.0.0
# sudo: required

language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql
script:
  - bundle exec rake spec
before_script:
  - bundle exec rake db:create RAILS_ENV=test
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
bundler_args: --binstubs=./bundler_stubs