# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b70c16a2a4556f8239496e6a5a661422287ab27da762d9e811c5c87c470427f233d01d502a1ead377a79ff8784c4fca489f6eb082ebf81eb1c21bf6e36a6c97
  stripe_publishable_key: pk_test_MTUjwzWwoWmhG6d1zR5Qci1s
  stripe_secret_key: sk_test_HN9jJtO1dsr7NNUE8oVHnWFg
  stripe_client_id: ca_5xdVXeNuvw5enletVQdYE3jyJnC6yOUq
  fee_percentage: 0.1

test:
  secret_key_base: 399b1bc9b33aef0460346e18774cb4a5128d5081b2e73cc6f54ee77984dc70dc7ce624adfa38b80229a196461ad1d05decd18a56b7980f64f17ebaff49826a70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
  email_provider_username: <%= ENV["GMAIL_USERNAME"] %>
  email_provider_password: <%= ENV["GMAIL_PASSWORD"] %>
  stripe_client_id: <%= ENV["STRIPE_CLIENT_ID"] %>
  redis_to_go_id: <%= ENV["REDISTOGO_URL"] %>

